import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { checkPolicy } from './check-policy.js';
import { checkBridge } from './check-bridge.js';
import { checkHttp, toolCount } from './check-http.js';
import { checkHttpBudgets } from './check-http-budgets.js';
import { checkContext, checkHistory } from './check-context.js';
import { checkEvents, checkCancellation } from './check-events.js';
import { checkEventsPump } from './check-events-pump.js';
import { checkAuth } from './check-auth.js';
import { checkMedia } from './check-media.js';
import { checkMediaLimits } from './check-media-limits.js';
import { checkControls } from './check-controls.js';
import { checkConnection } from './check-connection.js';
import { checkOAuth } from './check-oauth.js';
import { checkOperator } from './check-operator.js';
import { checkReplyOrigins } from './check-reply-origins.js';
import { checkProactive } from './check-proactive.js';
import { checkEnvironmentRestart, checkPeople } from './check-people.js';
import { checkPanel } from './check-panel.js';
import { checkController } from './check-controller.js';
import { checkProviderApproval } from './check-provider-approval.js';
import { checkCodexAdapter } from './check-codex-adapter.js';
import { checkClaudeAdapter } from './check-claude-adapter.js';
import { checkClaudeController } from './check-claude-controller.js';
import { checkInteractionEvents } from './check-interaction-events.js';
import { checkOwnerContext } from './check-owner-context.js';
import { checkEnvironmentRename, checkOnboarding } from './check-onboarding.js';
import { checkBridgeProcess, checkChannel } from './check-channel.js';
import { checkApps } from './check-apps.js';
import { checkSlashCommands } from './check-commands.js';
import { checkSessionActivity, checkSessions } from './check-sessions.js';
import { checkCodexDaemon } from './check-codex-daemon.js';
import { checkUi } from './check-ui.js';
import { checkEffects } from './check-effects.js';
import { checkReviewFlows } from './check-review.js';
import { checkRender } from './check-render.js';
import { checkDashboard } from './check-dashboard.js';
import { checkWindows } from './check-windows.js';
import { checkAccessRules } from './check-access-rules.js';
import { checkMessageOperations } from './check-message-operations.js';
import { checkAdminOperations } from './check-admin-operations.js';
import { checkDiscordApi } from './check-discord-api.js';
import { checkRuntimeLock } from './check-runtime-lock.js';
import { checkGatewayMessages } from './check-gateway-messages.js';
import { checkGatewayLoad } from './check-gateway-load.js';
import { checkGatewayInteractions } from './check-gateway-interactions.js';
import { checkGatewayLifecycle } from './check-gateway-lifecycle.js';
import { checkCoreEdges } from './check-core-edges.js';
import { checkWebhookHttps } from './check-webhook-https.js';
import { checkEventsDelivery } from './check-events-delivery.js';
import { checkEventsRules } from './check-events-rules.js';
import { checkMcpTools } from './check-mcp-tools.js';
import { checkMcpLocal } from './check-mcp-local.js';
import { checkMediaEdges } from './check-media-edges.js';
import { checkOAuthEdges } from './check-oauth-edges.js';
import { checkInteractionEdges } from './check-interaction-edges.js';
import { checkStatusFile } from './check-status-file.js';
import { checkServiceHost } from './check-service-host.js';
import { checkSupervisor } from './check-supervisor.js';
import { checkProviders } from './check-providers.js';
import { checkClaudePlugin } from './check-claude-plugin.js';
import { checkRecovery } from './check-recovery.js';
import { checkServers } from './check-servers.js';
import { checkOnboardingCopy } from './check-onboarding-copy.js';
import { checkOnboardingVerify } from './check-onboarding-verify.js';
import { checkOnboardingFlow } from './check-onboarding-flow.js';
import { checkOnboardingUi } from './check-onboarding-ui.js';

await mkdir('.data', { recursive: true, mode: 0o700 });
const directory = await mkdtemp(join('.data', 'validation-'));
try {
    await checkOAuth(directory);
    if (process.argv.includes('--oauth')) process.exitCode = 0;
    else {
        await checkHttp(directory);
        await checkHttpBudgets(directory);
        await checkAuth();
        await checkConnection(directory);
        if (process.argv.includes('--connection')) {
            console.log(
                'Connection validation passed: bearer HTTP, offline OAuth JWTs and hosting-independent configuration. No external connections.',
            );
        } else {
            await checkPolicy(directory);
            await checkBridge(directory);
            await checkContext(directory);
            await checkHistory(directory);
            await checkEvents(directory);
            await checkCancellation(directory);
            await checkEventsPump(directory);
            await checkEventsDelivery(directory);
            await checkEventsRules(directory);
            await checkWebhookHttps();
            await checkMedia(directory);
            await checkMediaLimits(directory);
            await checkMediaEdges(directory);
            await checkControls(directory);
            await checkOperator();
            await checkReplyOrigins(directory);
            await checkProactive(directory);
            await checkMcpTools(directory);
            await checkMcpLocal(directory);
            await checkPeople(directory);
            await checkEnvironmentRestart(directory);
            await checkPanel();
            await checkOnboarding();
            await checkEnvironmentRename(directory);
            await checkChannel(directory);
            await checkBridgeProcess(directory);
            await checkApps();
            await checkSlashCommands();
            await checkSessions();
            await checkSessionActivity(directory);
            await checkCodexDaemon();
            await checkWindows(directory);
            await checkAccessRules(directory);
            await checkStatusFile(directory);
            await checkServiceHost(directory);
            await checkSupervisor(directory);
            await checkProviders(directory);
            await checkClaudePlugin(directory);
            await checkRecovery(directory);
            await checkServers(directory);
            checkOnboardingCopy();
            await checkOnboardingVerify(directory);
            await checkOnboardingFlow(directory);
            await checkOnboardingUi(directory);
            checkUi();
            await checkEffects();
            await checkReviewFlows();
            await checkRender();
            await checkDashboard();
            await checkController(directory);
            await checkProviderApproval(directory);
            await checkCodexAdapter();
            await checkClaudeAdapter();
            await checkClaudeController(directory);
            await checkInteractionEvents(directory);
            await checkInteractionEdges(directory);
            await checkOwnerContext(directory);
            await checkMessageOperations(directory);
            await checkAdminOperations(directory);
            await checkDiscordApi();
            await checkRuntimeLock(directory);
            await checkGatewayMessages(directory);
            await checkGatewayLoad(directory);
            await checkGatewayInteractions(directory);
            await checkGatewayLifecycle(directory);
            await checkCoreEdges(directory);
            await checkOAuthEdges(directory);
            console.log(
                `Local validation passed: policy/triggers, Gateway mocks, approvals, idempotency, queue and bearer/OAuth MCP (${toolCount()} tools), context, MCP Events, safe media/retrieval and correlated controls. No Discord connection.`,
            );
        }
    }
} finally {
    await rm(directory, { recursive: true, force: true });
}
